#!/bin/bash

DIRS='
./BluetoothChatTechDemo/images
./Earthquake/images
./Evermore/data/images
./FragmentLifecycleToybox/images
./FragmentStorageDemo/images
./NfcReaderWriter/images
./ProductListTechDemo/images
'

for dir in $DIRS
do
  echo '--------'
  echo "DIR: $dir..."
  echo '--------'
  (
    cd $dir
    #mkdir screenshots
    #mv Screenshot*.png screenshots
  )

done
